spring.application.name=ehub

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://postgres:5432/ehub_db?options=-c%20TimeZone=UTC
spring.datasource.username=ehub_user
spring.datasource.password=ehub_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Import local configuration
spring.config.import=optional:classpath:application-local.properties